### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by VCwen123** [cppppp/STRANet#1]
Hello author, in your VTM code VVCSoftware_VTM-VTM-10.2-fast/source/Lib/EncoderLib
/EncCu.h has< int fastpartition[4][550][970][9][9][4][7]>. When VS generates the solution, it shows that the maximum size of the array is exceeded Capacity, resulting in failure to generate. I wonder if such a problem occurred when you were doing experiments.

**Comment by cppppp** [comment]
Since I implemented the code on linux, the problem did not occur. I may try to optimize the memory overhead in the future.

**Comment by VCwen123** [comment]
Thank you for your answer。 Recent ，I used the gen_file.py in the gen_file folder to predict the partition of 8 frames (you provided 4 frames for the city) and saved it and intended to apply it in VTM encoding
and modified "your_path", as well as int fastpartition[8][550][970][9][9][4][7];
  int chromapartition[8][40][70][5];  The number of frames in the number (4 has been changed to 8). But I found that the code you added read the saved file for a while loop
It will only read the content of 0-3 (the encoding interval is 8 by default), I use your code to predict the additional 4-7 frame division and will not read, resulting in a very slow encoding time,
I don't know what the problem is,I hope you can provide me with an answer, thank you!

**Comment by cppppp** [comment]
I think this is quite weird. Maybe there is some problem in the txt generated by the gen_file.py, and you may check the frame number and probabilities in your txt. I will also release a version that makes a prediction per frame in a week to avoid this problem.

**Comment by VCwen123** [comment]
ok ,thank you!

**Comment by cppppp** [comment]
I'm sorry that there was a bug in the last version, which has been corrected. I have confirmed that this version can generate correct results for 8 frames. You only need to edit the arguments in gen_file.py and split_txt.py to change to 8 frames, and the VTM does not need to be editted.

**Comment by VCwen123** [comment]
ok!
